theme: light

# One Light / Dark modified
colors:
  light:
    white: "FFFFFF"
    black: "000000"
    lightgreen: "00CC00"
    yellow: "FFDF00"
    magenta: "C800E2"
    blue: "005be4"
    gray: "808080"
    lightgray: "C0C0C0"
    red: "CC0000"
    green: "00CC00"
    cyan: "0088E2"
    foreground: "000000"
    primary: "0088E2"
    secondary: "C800E2"
  dark:
    white: "FFFFFF"
    black: "000000"
    lightgreen: "00CC00"
    yellow: "FFDF00"
    magenta: "C800E2"
    blue: "005be4"
    gray: "808080"
    lightgray: "C0C0C0"
    red: "EE0000"
    green: "00EE00"
    cyan: "5EBBF9"
    foreground: "FFFFFF"
    primary: "FFDF00"
    secondary: "5EBBF9"

# Flexoki
# colors:
#   light:
#     white: "FFFCF0"
#     black: "100F0F"
#     lightgreen: "879A39"
#     yellow: "AD8301"
#     magenta: "A02F6F"
#     blue: "205EA6"
#     gray: "6F6E69"
#     lightgray: "B7B5AC"
#     red: "AF3029"
#     green: "66800B"
#     cyan: "24837B"
#     foreground: "100F0F"
#     primary: "24837B"
#     secondary: "A02F6F"
#   dark:
#     white: "FFFCF0"
#     black: "100F0F"
#     lightgreen: "879A39"
#     yellow: "D0A215"
#     magenta: "CE5D97"
#     blue: "4385BE"
#     gray: "B7B5AC"
#     lightgray: "DAD8CE"
#     red: "D14D41"
#     green: "879A39"
#     cyan: "3AA99F"
#     foreground: "CECDC3"
#     primary: "D0A215"
#     secondary: "3AA99F"
