#!/usr/bin/env fish
#
# This file is part of fishamnium. Copyright (C) 2013 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

set rootdir ~/.fishamnium
set destdir /tmp/fishamnium-(date +%Y%m%d%H%M%S)

if [ "$FISHAMNIUM_OPERATION" = "uninstall" ]
  echo "* Removing directory $rootdir ..."; and /bin/rm -rf "$rootdir"
  echo -e "\n-------\n\nfishamnium has been uninstalled. Enabling it is left to you."
  echo -e "To enable, remove the following line to $HOME/.config/fish/config.fish:\n"
  echo -e "source ~/.fishamnium/loader.fish\n"
  echo -e "Hope you liked it. Farewell! ;)"
  exit 0
end

if [ "$FISHAMNIUM_LOCAL_INSTALL" = "" ]
  echo "Cloning fishamnium into $destdir"; and git clone https://github.com/ShogunPanda/fishamnium -q -- "$destdir"
  cd $destdir
else
  rake build:shell
end

rm -rf $rootdir
cp -a dist $rootdir

set os (uname -s)

switch (uname -s)
    case Linux
        ln -sf ~/.fishamnium/helpers/fishamnium-linux ~/.fishamnium/helpers/fishamnium
    case Darwin
        ln -sf ~/.fishamnium/helpers/fishamnium-darwin ~/.fishamnium/helpers/fishamnium
    case '*'
        ln -sf ~/.fishamnium/helpers/fishamnium-windows ~/.fishamnium/helpers/fishamnium
end

if [ "$FISHAMNIUM_LOCAL_INSTALL" = "" ]
  cd $HOME
  and /bin/rm -rf "$destdir"
end
