[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["install"]

[tasks.install]
  dependencies = ["build:macos"]
  command      = "./installer"
  args         = ["-l"]

[tasks.build]
  dependencies = ["build:macos", "build:linux"]

[tasks."build:macos"]
  script = '''
mkdir -p dist
cargo build --manifest-path helper/Cargo.toml --release --target aarch64-apple-darwin
cp helper/target/aarch64-apple-darwin/release/fishamnium dist/fishamnium-macos
'''

# To enable compilation on Mac:
# brew install x86_64-unknown-linux-gnu
# brew trust messense/macos-cross-toolchains
# brew tap messense/macos-cross-toolchains
[tasks."build:linux"]
  env = { CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER = "x86_64-unknown-linux-gnu-gcc" }
  script = '''
mkdir -p dist
cargo build --manifest-path helper/Cargo.toml --release --target x86_64-unknown-linux-gnu
cp helper/target/x86_64-unknown-linux-gnu/release/fishamnium dist/fishamnium-linux
'''

[tasks.deploy]
  dependencies = ["version:bump", "release", "install"]

[tasks.pack]
  dependencies = ["build"]
  env          = { COPYFILE_DISABLE = "1" }
  command      = "tar"
  args         = ["--no-xattrs", "--exclude='*/.*'", "--exclude='.*'", "--exclude=helper/target", "-czvf", "fishamnium.tar.gz", "completions", "data", "default.yml", "installer", "LICENSE.md", "loader.fish", "plugins", "themes", "version"]

[tasks."version:bump"]
  script_runner = "@duckscript"
  script = """
    if is_empty ${1}
      exec cambi update -o -l -t
    else
      valid_tags = array major minor patch
      valid = array_contains ${valid_tags} ${1}
      
      if not ${valid}
        trigger_error "Usage: makers version [type=major|minor|patch]"
      end
      
      exec cambi update -o -l -t ${1}
    end
  """

[tasks.release]
  dependencies = ["pack"]
  script_runner = "@duckscript"
  script = """
    version = readfile ./version
    version = trim ${version}
    notes = exec cambi release -n
    writefile release-notes.txt ${notes}

    exec git push origin
    exec git push origin -f --tags
	  exec gh release create "v${version}" -t "${version}" -F release-notes.txt fishamnium.tar.gz dist/fishamnium-macos dist/fishamnium-linux    
    exec rm -f fishamnium.tar.gz release-notes.txt
  """
