# ----- Aliases -----

alias clcd='clear; cd'
alias clf='printf "\033c"'
alias cdc='cd $(pwd)'
alias cdf='pushd'
alias cdb='popd'
alias cdl='popd'
alias cdy='pwd | fish_clipboard_copy'
alias cdn='basename $(pwd)'
alias cp='cp -R -v -i'
alias mv='mv -v -i'
alias rm='rm -R'
alias ls='/bin/ls -h -F'
alias sudo='sudo -H'
alias eol='execute_on_list'
