#!/usr/bin/env fish
#
# This file is part of fishamnium. Copyright (C) 2013 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#


complete -c fishamnium_git -n "" -s q -l quiet -d "Be more quiet."
complete -c fishamnium_git -n "" -s n -l dry-run -d "Do not execute write action."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "is_repository ir" -d "Check if the current directory is a GIT repository."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "is_dirty id" -d "Check if the current GIT repository has uncommitted changes."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "remotes lr" -d "Show GIT remotes."
complete -c fishamnium_git -n "__fishamnium_completion_is_command remotes lr" -s a -l autocomplete -d "Format for autocompletion."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "full_branch_name fbn" -d "Get the full current branch name."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "branch_name bn" -d "Get the current branch name."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "full_sha" -d "Get the full current GIT SHA."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "sha" -d "Get the current GIT SHA."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "summary ls" -d "Get a summary of current GIT repository branch, SHA and dirty status."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "task t" -d "Get the current task name from the branch name."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "commit_with_task ct" -d "Commit changes including the task name."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "commit_all_with_task cat" -d "Commit all changes including the task name."
complete -c fishamnium_git -n "__fishamnium_completion_is_command commit_all_with_task cat" -s a -l add-all -d "Add all files before commiting."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "reset re" -d "Reset all uncommitted changes."
complete -f -c fishamnium_git -n "__fishamnium_completion_is_global" -a "cleanup cl" -d "Deletes all non default branches."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "update u" -d "Fetch from remote and pulls a a branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command update u" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "push p" -d "Pushes the current branch to the remote."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command push p" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -c fishamnium_git -n "__fishamnium_completion_is_command push p" -s f -l force -d "If to perform a force push."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "delete d" -d "Deletes one or more branch both locally and on a remote."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command delete d" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "start s" -d "Starts a new branch out of the base one."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command start s" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "refresh r" -d "Rebases the current branch on top of an existing remote branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command refresh r" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "finish f" -d "Merges a branch back to its base remote branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command finish f" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "full_finish ff" -d "Merges a branch back to its base remote branch and then deletes the local copy."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command full_finish ff" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "fast_commit fc" -d "Creates a local branch, commit changes and then merges it back to the base branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command fast_commit fc" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "pull_request pr" -d "Sends a Pull Request and deletes the local branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command pull_request pr" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "fast_pull_request fpr" -d "Creates a local branch, commit changes and then sends a Pull Request, deleting the local branch at the end."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command fast_pull_request fpr" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "release rt" -d "Tags and pushes a new release branch out of the base one."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command release rt" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command release rt" -s p -l prefix -d "The prefix to use."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "import i" -d "Imports latest changes to a local branch on top of an existing remote branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command import i" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command import i" -s t -l temporary -d "Name of the temporary branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "start_from_release rs" -d "Starts a new branch out of a remote release branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command start_from_release rs" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command start_from_release rs" -s p -l prefix -d "The prefix to use."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "refresh_from_release rr" -d "Rebases the current branch on top of an existing remote release branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command refresh_from_release rr" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command refresh_from_release rr" -s p -l prefix -d "The prefix to use."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "finish_to_release rf" -d "Merges a branch back to its base remote release branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command finish_to_release rf" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command finish_to_release rf" -s p -l prefix -d "The prefix to use."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "full_finish_to_release rff" -d "Merges a branch back to its base remote release branch and then deletes the local copy."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command full_finish_to_release rff" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command full_finish_to_release rff" -s p -l prefix -d "The prefix to use."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "import_release ri" -d "Imports latest changes to a local branch on top of an existing remote release branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command import_release ri" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command import_release ri" -s p -l prefix -d "The prefix to use."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command import_release ri" -s t -l temporary -d "Name of the temporary branch."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_global" -a "delete_release rd" -d "Deletes a release branch locally and remotely."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command delete_release rd" -s r -l remote -a "(fishamnium_git lr -a)" -d "The remote to act on."
complete -x -c fishamnium_git -n "__fishamnium_completion_is_command delete_release rd" -s p -l prefix -d "The prefix to use."
