add_newline = false
scan_timeout = 100
command_timeout = 500

# Summary:
#
# 2022-01-20 13:38:18 /full/path branch sha x
# user @host version:number version:number >
format = """
$time$directory$git_branch$git_commit[\ue0b4](fg:#005be4) $git_status
$username$hostname($nodejs$rust$ruby$golang)[ ](fg:#000000 bg:#ffdf00)[\ue0b0 ](bold fg:#ffdf00)
""" 

[time]
format="[\ue0b6](bold fg:#013482)[ \uf64f $time ](bold fg:#ffffff bg:#013482)"
time_format = '%F %T'
disabled = false

[directory]
format="[\ue0c0](fg:#013482 bg:#005be4)[ \uf114 $path ](bold fg:#ffffff bg:#005be4)"
truncation_length = 3
truncation_symbol = ""
truncate_to_repo = false

[git_branch]
format = "[\ue0a0 $branch ](bold fg:#ffffff bg:#005be4)"
only_attached = true

[git_commit]
format = "[$hash ](bold fg:#ffffff bg:#005be4)"
only_detached = false

[git_status]
format = "($untracked)($conflicted)($modified)"
modified = "\U0001F538"
untracked = "\U0001F539"
conflicted = "\U0001F53A"
ahead=""
behind=""
diverged=""

[username]
style_user = "#008800"
style_root = "#cc0000"
format = "[\ue0b6](bold fg:$style)[ \uf007 $user ](bold fg:#ffffff bg:$style)[\ue0b4](fg:$style bg:#ffdf00)"
disabled = false
show_always = true

[hostname]
format = "[ \uf502 $hostname ](bold fg:#000000 bg:#ffdf00)"
ssh_only = false

[nodejs]
format = "[ node:$version](fg:#000000 bg:#ffdf00)"
version_format = "$raw"

[ruby]
format = "[ ruby:$version](fg:#000000 bg:#ffdf00)"
version_format = "$raw"

[rust]
format = "[ rust:$version](fg:#000000 bg:#ffdf00)"
version_format = "$raw"

[golang]
format = "[ go:$version](fg:#000000 bg:#ffdf00)"
version_format = "$raw"