add_newline     = false
scan_timeout    = 100
command_timeout = 500

# Summary:
#
# user @host x
format = "$username$hostname$git_status[ ](fg:#000000 bg:#ffdf00)[\ue0b0 ](bold fg:#ffdf00)"

[username]
  style_user  = "#008800"
  style_root  = "#cc0000"
  format      = "[\ue0b6](bold fg:$style)[ \uf007 ](bold fg:#ffffff bg:$style)[\ue0b4](bold fg:$style bg:#ffdf00)"
  disabled    = false
  show_always = true

[hostname]
  format   = "[ \uef09 $hostname ](bold fg:#000000 bg:#ffdf00)"
  ssh_only = false

[git_status]
  format     = "([ \ue0a0 ($untracked)($conflicted)($modified)](bg:#ffdf00))"
  modified   = "\U0001F538"
  untracked  = "\U0001F539"
  conflicted = "\U0001F53A"
  ahead      = ""
  behind     = ""
  diverged   = ""
